<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p</name>
   <tag></tag>
   <elementGuidId>0b286e4c-d71a-4bb9-bff1-299271c2104d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='FormApproverHideShow1']/div/div[2]/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.single-notes-content > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>115e7a7c-a864-4305-b6f5-5e4157cc6803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormApproverHideShow1&quot;)/div[@class=&quot;single-notes alert&quot;]/div[@class=&quot;single-notes-body&quot;]/div[@class=&quot;single-notes-content&quot;]/p[1]</value>
      <webElementGuid>53ba8fe3-df93-46e9-870e-c9d717198987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormApproverHideShow1']/div/div[2]/div[2]/p</value>
      <webElementGuid>b29c80b6-449d-413b-b0ac-88547cd5c9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Inbox'])[1]/following::p[1]</value>
      <webElementGuid>622b8178-adf2-44ee-bcd9-b4f1dc78f012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click Here to View Approval Flow'])[1]/following::p[1]</value>
      <webElementGuid>9c613614-193f-4c8c-b03e-9756ccb36a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advance Payment'])[1]/preceding::p[1]</value>
      <webElementGuid>9887370a-d8ea-4f10-a18e-7a98a2b99b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request'])[1]/preceding::p[1]</value>
      <webElementGuid>847e7029-c1b8-4b53-b143-a7beaa3ba9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>3acd38ba-8add-4974-a12d-c952d1fa3519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
