<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-Select-</name>
   <tag></tag>
   <elementGuidId>242ff8f1-689b-4693-a036-cec634233693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-ddlSubject-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-ddlSubject-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>54da6615-ba3b-4ccd-9d69-425e12ddff65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>c3c80828-4115-4b6d-9024-118a62d9c153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ddlSubject-container</value>
      <webElementGuid>ba964f61-82a2-4948-b519-35ace3f7bdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>0236774c-f6cd-4fd9-af8b-58919b707500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>6d5fcf35-fe45-4b22-8d12-6c35004ee66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ddlSubject-container&quot;)</value>
      <webElementGuid>4fb6be3e-faaa-4bca-8106-5f45a510c009</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-ddlSubject-container']</value>
      <webElementGuid>4cc16927-d786-41a3-afee-9a77fefae1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div/div/div[5]/div/span/span/span/span</value>
      <webElementGuid>6dbb6690-7151-4890-b748-d6b9cefcb329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/preceding::span[3]</value>
      <webElementGuid>e09b0b2f-7363-4d2b-8760-a3197c461873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>fd8f9eef-a7c9-4aa7-842e-64d7644e5eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-ddlSubject-container' and @title = '-Select-' and (text() = '-Select-' or . = '-Select-')]</value>
      <webElementGuid>f8344c80-abd0-4f09-84da-a989d7ceaf5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
