<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Lakshmi_fa fa-check-square</name>
   <tag></tag>
   <elementGuidId>7e2d64bc-2d3c-48cd-a425-18f6e974951f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='grdApproval']/tbody/tr/td[5]/a/center/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-check-square</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>61e3b07c-43ea-433c-9863-071686908c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-check-square</value>
      <webElementGuid>cf11cf8c-76e8-4fa4-a82d-07faae0d7a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>859a78b2-38a5-474c-aa53-a0a9dfa721f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdApproval&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;empname&quot;]/a[1]/center[1]/i[@class=&quot;fa fa-check-square&quot;]</value>
      <webElementGuid>0495aa3b-18f8-4c7f-b86f-38cf5549a7c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='grdApproval']/tbody/tr/td[5]/a/center/i</value>
      <webElementGuid>08dce2a6-10a8-45a6-940b-d4369e8dbd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/i</value>
      <webElementGuid>3f2a1d93-97c5-464b-9cb2-98eb3035712c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
