<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__BtnLogin</name>
   <tag></tag>
   <elementGuidId>6e8940e9-becb-47e1-ad78-dc0b07ae50c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BtnLogin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnLogin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc4bae71-84a6-4831-8714-fce85ce3b308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnLogin</value>
      <webElementGuid>29547ec8-65cc-4b3b-8f91-bb9a67169d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>69d01a32-af99-4a01-a61a-10a122f3ca13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn submit overlay</value>
      <webElementGuid>10e5fd4a-e685-4831-bcc2-4b6d7842803b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BtnLogin</value>
      <webElementGuid>696e604b-0449-4a5b-9db7-7e146809ec66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>e68cdf79-dfdd-4411-9b01-3f25b81f2256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnLogin&quot;)</value>
      <webElementGuid>49202634-7c3e-47e3-ab3f-9d2ece5db246</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BtnLogin']</value>
      <webElementGuid>727c5471-1637-45ef-a06d-b37608521053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>e9211668-f360-4891-95fc-0178b89b76b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BtnLogin' and @type = 'submit' and @name = 'BtnLogin']</value>
      <webElementGuid>a30dcd2c-40d2-4f36-b58a-74f867887e5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
