<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p</name>
   <tag></tag>
   <elementGuidId>ff896af1-0f97-40b1-9c50-20a3431a2804</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='FormApproverHideShow1']/div/div[2]/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.single-notes-content > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>798e3ad1-13b8-4424-b24a-0c1c46c02888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormApproverHideShow1&quot;)/div[@class=&quot;single-notes alert&quot;]/div[@class=&quot;single-notes-body&quot;]/div[@class=&quot;single-notes-content&quot;]/p[1]</value>
      <webElementGuid>d90c783e-73cb-4560-9b63-c5d88ad45e4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormApproverHideShow1']/div/div[2]/div[2]/p</value>
      <webElementGuid>e9e034eb-0919-4ddf-afcb-54369bd8df2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Inbox'])[1]/following::p[1]</value>
      <webElementGuid>45b97741-d8b5-4529-b223-e485e47f261a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click Here to View Approval Flow'])[1]/following::p[1]</value>
      <webElementGuid>69b53fdf-d0c7-4c12-b998-800d74fdd4b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advance Payment'])[1]/preceding::p[1]</value>
      <webElementGuid>dca67abd-1ffa-4d65-a574-f6e69fad96d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request'])[1]/preceding::p[1]</value>
      <webElementGuid>6ce7185b-00e6-4e4f-85f8-4c34b90780f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>45542599-4f88-410a-8df4-b3c28bdd24a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
