<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Leave Calender_Leave Request</name>
   <tag></tag>
   <elementGuidId>489e151c-c45b-4f56-a751-fdb905d3af6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnNewLeavRQ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnNewLeavRQ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d0f3913-4fd4-4792-8362-856be77eff8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnNewLeavRQ</value>
      <webElementGuid>18aaa718-d6c3-43b3-a211-a0a3612ac099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ece851a3-9d75-4e69-8d27-f35b02d56fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>37eae886-e4d5-4da0-851c-2510879db22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Leave Request</value>
      <webElementGuid>cb9badc7-8009-4853-a22f-926edb9cb4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Leave Request</value>
      <webElementGuid>468e89be-c3bd-4a9e-8979-d4c55473d6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnNewLeavRQ&quot;)</value>
      <webElementGuid>fa6a04f0-01ca-460e-8eb5-5d4c65e6894d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnNewLeavRQ']</value>
      <webElementGuid>db74e746-3dbf-417e-870f-83ff750c16f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>9e38e321-c89b-4397-ba95-a4f87494b099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>9b778ddf-5812-41bf-8981-14d94e36d525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'btnNewLeavRQ' and @type = 'button' and @name = 'Leave Request']</value>
      <webElementGuid>6b2db15e-72fc-491d-87ca-032d8d91e87b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
