<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p</name>
   <tag></tag>
   <elementGuidId>e0cab82b-1128-4068-9066-b1e239e057d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pnlImgSlider1']/div/div[7]/div/div[2]/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ecfe145e-9b27-41c5-8bf8-e44cea90f355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pnlImgSlider1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;single-notes alert&quot;]/div[@class=&quot;single-notes-body&quot;]/div[@class=&quot;single-notes-content&quot;]/p[1]</value>
      <webElementGuid>cdd07a8b-1a0d-4c94-80dc-be19b901661b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pnlImgSlider1']/div/div[7]/div/div[2]/div[2]/p</value>
      <webElementGuid>be9ecaef-3191-4f28-abf2-203a7ac7e5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Details'])[1]/following::p[1]</value>
      <webElementGuid>cb1bff9f-fb9e-4c5a-9b6f-4a7dbc873687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[2]/following::p[1]</value>
      <webElementGuid>ee251fc8-eb8b-4a06-a0e5-16605dcff21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request'])[3]/preceding::p[1]</value>
      <webElementGuid>bdf189ef-b814-4053-9582-0d90bfd8ccf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div[2]/p</value>
      <webElementGuid>9c7119bd-09a5-4215-b461-3d50fdda7ecf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
