<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-Select-EARNED LEAVEMATERNITY LEAVEH_3bb99f</name>
   <tag></tag>
   <elementGuidId>c95be10d-45a2-4fb3-9945-a9470a098117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddlLeaveType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ddlLeaveType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8aedc150-1159-4345-bee6-8e0957464719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e892e7eb-ebf3-46be-a58f-0536609719b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlLeaveType</value>
      <webElementGuid>0252a3d4-8dcf-4b2c-8ef6-19c8fbb96203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LeaveType</value>
      <webElementGuid>f34c9191-bee1-4560-82c6-980d6f4ec40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CalLeaveAvailabl()</value>
      <webElementGuid>a602a59c-6c2e-456a-a142-e4def1b27a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Select-EARNED LEAVEMATERNITY LEAVEHALF PAY LEAVEFULL PAY LEAVESPECIAL CASUAL LEAVEEXTRAORDINARY LEAVE(LWA)CASUAL LEAVECOMPENSATORY HOLIDAYSPECIAL DISABILITY LEAVESTUDY LEAVECHILD CARE LEAVE</value>
      <webElementGuid>ad6a4de3-0ae0-4523-9d76-4175114b5e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlLeaveType&quot;)</value>
      <webElementGuid>69623659-c010-4dab-aa64-a706fd493032</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddlLeaveType']</value>
      <webElementGuid>d36de71f-1dc1-4e15-aca7-051426478777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Createpage']/div[2]/div/select</value>
      <webElementGuid>22247387-87bb-476a-b43f-a4f0bdd3f32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>53a7599e-9872-4648-bf69-1d3ce98d6c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaves Available:'])[1]/preceding::select[1]</value>
      <webElementGuid>6a07b0db-da07-404c-9ad7-53162a66d61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b16820e9-f9d2-4165-871c-8edc00a29e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ddlLeaveType' and @name = 'LeaveType' and (text() = '-Select-EARNED LEAVEMATERNITY LEAVEHALF PAY LEAVEFULL PAY LEAVESPECIAL CASUAL LEAVEEXTRAORDINARY LEAVE(LWA)CASUAL LEAVECOMPENSATORY HOLIDAYSPECIAL DISABILITY LEAVESTUDY LEAVECHILD CARE LEAVE' or . = '-Select-EARNED LEAVEMATERNITY LEAVEHALF PAY LEAVEFULL PAY LEAVESPECIAL CASUAL LEAVEEXTRAORDINARY LEAVE(LWA)CASUAL LEAVECOMPENSATORY HOLIDAYSPECIAL DISABILITY LEAVESTUDY LEAVECHILD CARE LEAVE')]</value>
      <webElementGuid>2ebe42d9-7fb8-44f9-8138-4f14db40e711</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
